LIBS=-latmos -L/usr/local/lib/ -I/usr/local/include -lssl -lcurl 

atmos_create01: create01.c
	gcc -g -o create create01.c ${INC} ${LIBS}
read01: read01.c
	gcc -g -o read read01.c ${INC} ${LIBS}
update01: update01.c
	gcc -g -o update update01.c ${INC} ${LIBS}
delete01: delete01.c
	gcc -g -o delete delete01.c ${INC} ${LIBS}
